# Generated by Django 4.0.2 on 2022-02-10 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='feature_image',
            field=models.ImageField(default='images/default.png', upload_to='images/'),
        ),
    ]
